---
title: "Assignment 6"
author: "Harlett, McKinley"
date: "2021-01-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Set the working directory to the root of your DSC 520 directory
setwd("/Users/mckinleyharlett/Documents/Bellevue Grad Courses/Winter semester/Statistics in Data Science/GitHub Assignments/dsc520/dsc520/data")

## Load the `data/r4ds/heights.csv` to
heights_df <- read.csv("r4ds/heights.csv")
```

```{r}
## Load the ggplot2 library
library(ggplot2)
```

```{r}
## Fit a linear model using the `age` variable as the predictor and `earn` as the outcome
age_lm <-  lm(earn~age, data = heights_df)

## View the summary of your model using `summary()`
summary(age_lm)

```

```{r}
## Creating predictions using `predict()`
age_predict_df <- data.frame(earn = predict(age_lm), age=heights_df$age)

## Plot the predictions against the original data
ggplot(data = age_lm, aes(y = earn, x = age)) +
  geom_point(color='blue') +
  geom_line(color='red',data = age_predict_df, aes(y=earn, x=age))
```

```{r}
mean_earn <- mean(heights_df$earn)
mean_earn
```

```{r}
## Corrected Sum of Squares Total
sst <- sum((mean_earn - heights_df$earn)^2)
sst
```

```{r}
## Corrected Sum of Squares for Model
ssm <- sum((mean_earn - age_predict_df$earn)^2)
ssm
```

```{r}
## Residuals
residuals <- heights_df$earn - age_predict_df$earn
```

```{r}
## Sum of Squares for Error
sse <- sum(residuals^2)
sse
```

```{r}
## R Squared R^2 = SSM\SST
r_squared <- ssm/sst
```

```{r}
## Number of observations
n <- nrow(heights_df)
n
## Number of regression parameters
p <- 2
p
## Corrected Degrees of Freedom for Model (p-1)
dfm <- (p - 1)
dfm
## Degrees of Freedom for Error (n-p)
dfe <- (n - p)
dfe
## Corrected Degrees of Freedom Total:   DFT = n - 1
dft <- n - 1
dft
```

```{r}
## Mean of Squares for Model:   MSM = SSM / DFM
msm <- ssm/dfm
msm
## Mean of Squares for Error:   MSE = SSE / DFE
mse <- sse/dfe
mse
## Mean of Squares Total:   MST = SST / DFT
mst <- sst/dft
mst
## F Statistic F = MSM/MSE
f_score <- msm/mse
f_score
```

```{r}
## Adjusted R Squared R2 = 1 - (1 - R2)(n - 1) / (n - p)
adjusted_r_squared <- 1 - ((1 - r_squared)*(n - 1)) / (n - p)
adjusted_r_squared
```

```{r}
## Calculate the p-value from the F distribution
p_value <- pf(f_score, dfm, dft, lower.tail=F)
p_value
```
